INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (1, 'amazon-devices', 'Amazon Devices', 1);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (2, 'fashion', 'Amazon Fashion', 1);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (3, 'amazon-global-store', 'Amazon Global Store', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (4, 'pantry', 'Amazon Pantry', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (5, 'appliances', 'Appliances', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (6, 'mobile-apps', 'Apps & Games', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (7, 'baby', 'Baby', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (8, 'beauty', 'Beauty', 1);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (9, 'books', 'Books', 1);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (10, 'automotive', 'Car & Motorbike', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (11, 'apparel', 'Clothing & Accessories', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (12, 'collectibles', 'Collectibles', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (13, 'computers', 'Computers & Accessories', 1);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (14, 'electronics', 'Electronics', 1);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (15, 'furniture', 'Furniture', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (16, 'lawngarden', 'Garden & Outdoors', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (17, 'gift-cards', 'Gift Cards', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (18, 'grocery', 'Grocery & Gourmet Foods', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (19, 'hpc', 'Health & Personal Care', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (20, 'kitchen', 'Home & Kitchen', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (21, 'industrial', 'Industrial & Scientific', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (22, 'jewelry', 'Jewellery', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (23, 'digital-text', 'Kindle Store', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (24, 'luggage', 'Luggage & Bags', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (25, 'luxury-beauty', 'Luxury Beauty', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (26, 'dvd', 'Movies & TV Shows', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (27, 'popular', 'Music', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (28, 'mi', 'Musical Instruments', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (29, 'office-products', 'Office Products', 0);
INSERT INTO amazon.Categories (id, name, displayName, isEnabled) VALUES (30, 'pets', 'Pet Supplies', 0);